name: ls
on: 
    push:

jobs:
    ls:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v3
            - run: cd templates && ls -1 | grep -v 'ls' > ls
            - run: cd features && ls -1 | grep -v 'ls' > ls
            - run: cd addons && ls -1 | grep -v 'ls' > ls
            - uses: stefanzweifel/git-auto-commit-action@v5
